extends PlatformerLevel
## Level 1 — Stomp Road. A classic side-scrolling platformer run.
## Layout lives in level_01_map.txt (generated by tools/level_01_layout.py; see the legend
## in PlatformerLevel). Edit the generator, re-run it, and the level rebuilds on next play.
##
## Ending: a portal tears open at the castle, the cheerful mushroom world morphs into clean
## future-tech under a hazy battle sky, and the hero walks through into Level 2's invasion.

const MAP_PATH := "res://scenes/levels/level_01/level_01_map.txt"
const WALK_SPEED := 3.2

var _results: Control
var _cutscene_running := false


func get_map() -> PackedStringArray:
	var text := FileAccess.get_file_as_string(MAP_PATH)
	return text.strip_edges(false, true).split("\n")


func _after_goal() -> void:
	_results = hud.show_level_results(coins, Game.elapsed, Game.deaths, "ENTER THE PORTAL", _portal_cutscene)


func _portal_cutscene() -> void:
	if _cutscene_running:
		return
	_cutscene_running = true
	_results.queue_free()
	Input.mouse_mode = Input.MOUSE_MODE_HIDDEN

	var castle_x := map_width_cells * PlatformerArt.CELL - 12.0
	var ground_y := 2 * PlatformerArt.CELL
	var portal := Portal.new()
	portal.radius = 2.3
	add_child(portal)
	portal.global_position = Vector3(castle_x, ground_y + 2.5, 0.6)
	hero.visual_root.rotation.y = PI * 0.5  # Face the castle.
	hero.skin.update_locomotion(0.0)
	hud.toast("WHAT IS THAT?!", Color(0.6, 0.9, 1.0))
	await portal.open(1.1)

	morph_world(3.5)
	hero.skin.update_locomotion(WALK_SPEED)
	var target_x := castle_x - 0.4
	var walk := create_tween()
	walk.tween_property(hero, "global_position:x", target_x, maxf(target_x - hero.global_position.x, 0.5) / WALK_SPEED)
	await walk.finished

	# Step into the light.
	var enter := create_tween().set_parallel()
	enter.tween_property(hero.visual_root, "scale", Vector3.ZERO, 0.45).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_IN)
	enter.tween_property(hero, "global_position:y", ground_y + 1.0, 0.45)
	await enter.finished
	await get_tree().create_timer(0.5).timeout
	Game.start_level(&"level_02")


## Turns the mushroom world into white/steel future-tech panels under a hazy, smoky sky.
func morph_world(duration: float) -> void:
	var tween := create_tween().set_parallel().set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)
	var haze := Color(0.88, 0.76, 0.62)
	tween.tween_property(sky_material, "sky_top_color", Color(0.38, 0.52, 0.72), duration)
	tween.tween_property(sky_material, "sky_horizon_color", haze, duration)
	tween.tween_property(sky_material, "ground_horizon_color", haze, duration)
	tween.tween_property(sky_material, "ground_bottom_color", Color(0.45, 0.47, 0.5), duration)
	tween.tween_property(environment, "fog_light_color", haze, duration)
	tween.tween_property(environment, "fog_density", 0.007, duration)
	tween.tween_property(sun, "light_color", Color(1.0, 0.9, 0.78), duration)

	var panels := {
		&"grass": [Color(0.86, 0.88, 0.9), Color(0.3, 0.75, 0.95)],
		&"dirt": [Color(0.55, 0.6, 0.66), Color(0.4, 0.45, 0.52)],
		&"brick": [Color(0.78, 0.8, 0.84), Color(0.35, 0.6, 0.85)],
		&"question": [Color(1.0, 0.8, 0.3), Color(0.3, 0.75, 0.95)],
		&"used": [Color(0.6, 0.64, 0.7), Color(0.45, 0.5, 0.58)],
		&"hard": [Color(0.7, 0.74, 0.8), Color(0.3, 0.75, 0.95)],
	}
	for kind: StringName in panels:
		var material := PlatformerArt.tile_material(kind)
		tween.tween_property(material, "shader_parameter/base_color", panels[kind][0], duration)
		tween.tween_property(material, "shader_parameter/edge_color", panels[kind][1], duration)
		tween.tween_property(material, "shader_parameter/edge_emission", 0.4, duration)
	for material in PlatformerArt.cached_flat_materials():
		if material.emission_enabled:
			continue  # Coins, portal glow etc. keep shining.
		tween.tween_property(material, "albedo_color", material.albedo_color.lerp(Color(0.62, 0.67, 0.74), 0.65), duration)
