extends PlatformerLevel
## Level 1 — Stomp Road. A classic side-scrolling platformer run.
## Layout lives in level_01_map.txt (generated by tools/level_01_layout.py; see the legend
## in PlatformerLevel). Edit the generator, re-run it, and the level rebuilds on next play.

const MAP_PATH := "res://scenes/levels/level_01/level_01_map.txt"


func get_map() -> PackedStringArray:
	var text := FileAccess.get_file_as_string(MAP_PATH)
	return text.strip_edges(false, true).split("\n")
